FROM maven:3.9.0-eclipse-temurin-17 AS builder
WORKDIR /build
COPY . /build
RUN mvn -B -DskipTests package

FROM eclipse-temurin:17-jdk-alpine
EXPOSE 8080
ENV APP_HOME /usr/src/app
COPY --from=builder /build/target/*.jar $APP_HOME/app.jar
WORKDIR $APP_HOME
CMD ["java", "-jar", "app.jar"]
