CREATE TABLE IF NOT EXISTS USERS (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255),
  password VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS POST (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  content CLOB,
  created_at TIMESTAMP,
  user_id BIGINT,
  CONSTRAINT fk_post_user FOREIGN KEY (user_id) REFERENCES USERS(id)
);
